language: go
sudo: false
go:
- 1.7
- 1.8
- tip
env:
  global:
  - GO15VENDOREXPERIMENT=1
  - TEST_TIMEOUT_SCALE=10
cache:
  directories:
  - vendor
install:
- mv $GOPATH/src/github.com/tracerun/tracerun $GOPATH/src/
- cd $GOPATH/src/tracerun
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
- glide install
- go install ./vendor/github.com/mattn/goveralls
script:
- go test -race -v
after_success:
- goveralls -service=travis-ci
notifications:
  slack:
    secure: VoYHZwIGffj2D2BxQmdQK3Ou06MDSDLwskw0ryhKdhVgcaW4N0JRSdl7OMhZ1JO1s6fAZCI9Fh1lzgjyefBl1phQ1zkvFnhAs9H9Aq5bQifUurLWeg1k3Q0vQx4+URml1qOcyPqqcv7oONtxWVme3uQUwYEFJ6sKRpy37GLesMJCuuWNzFFjJBaF9WG2bNM9ShULdQZcos5EPsuaBZZJmP5SO0osYJgxbsX2erUM2/srG11q0+SkYF1SeCdy5ssU3fCxmScrfGbfBi/cxxZH2d2yT9zamu41zGpxKW/iKKTSc5enOBx0z5jsmefsjjMVaDCpDBO7MiUkcnuodft/bcxsmFIQFTnkmInGz74W4M/o2IIulmXACVjjYz88RFbILlgWMkBadfNvlIoHQLFOd1Knur5e+jLBgTVykFccsJ3sHH94CQOYOOLQT4CPvsVySWuJiwp6+FL/rGNGYbm5Lo2ds/e+JJdxFprZDedBBZIokE5WAugd7ji5rKESS6AOiULoAesmiVdfVW7d/FKuxap8L2BKDxyuNpdOZOyLUAA+6e1piFxpFrsGoyanQpNqVo4g+eit09E/LS8HjAReXiqbfSGwUQ0FJccpNmoE8GzKfYFT3+CRtoWYbnx2lxq9ZF3yrwM1mOdLByA1SGjbC2EhIMmSfHCizNcddrfK9qs=
