// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Action
	AllActions
	ErrorMessage
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Action struct {
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Active bool   `protobuf:"varint,2,opt,name=active" json:"active,omitempty"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Action) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Action) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type AllActions struct {
	Actions []*AllActions_Act `protobuf:"bytes,1,rep,name=actions" json:"actions,omitempty"`
}

func (m *AllActions) Reset()                    { *m = AllActions{} }
func (m *AllActions) String() string            { return proto.CompactTextString(m) }
func (*AllActions) ProtoMessage()               {}
func (*AllActions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllActions) GetActions() []*AllActions_Act {
	if m != nil {
		return m.Actions
	}
	return nil
}

type AllActions_Act struct {
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Start  uint32 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	Last   uint32 `protobuf:"varint,3,opt,name=last" json:"last,omitempty"`
}

func (m *AllActions_Act) Reset()                    { *m = AllActions_Act{} }
func (m *AllActions_Act) String() string            { return proto.CompactTextString(m) }
func (*AllActions_Act) ProtoMessage()               {}
func (*AllActions_Act) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *AllActions_Act) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *AllActions_Act) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *AllActions_Act) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type ErrorMessage struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ErrorMessage) Reset()                    { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string            { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()               {}
func (*ErrorMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ErrorMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Action)(nil), "service.Action")
	proto.RegisterType((*AllActions)(nil), "service.AllActions")
	proto.RegisterType((*AllActions_Act)(nil), "service.AllActions.Act")
	proto.RegisterType((*ErrorMessage)(nil), "service.ErrorMessage")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xb1, 0xaa, 0xc2, 0x30,
	0x14, 0x86, 0xc9, 0xed, 0xbd, 0xed, 0xbd, 0xe7, 0xda, 0x25, 0x88, 0x06, 0xa7, 0xd2, 0x29, 0x53,
	0x41, 0x5d, 0x5c, 0x33, 0x88, 0x93, 0x4b, 0xde, 0x20, 0x86, 0x50, 0x0a, 0xd5, 0xc8, 0xc9, 0xa1,
	0xcf, 0xe0, 0x63, 0x8b, 0x49, 0x8a, 0x93, 0xdb, 0xff, 0xfd, 0xfc, 0xc9, 0xc7, 0x81, 0x3a, 0x38,
	0x9c, 0x06, 0xeb, 0xba, 0x3b, 0x7a, 0xf2, 0xbc, 0xca, 0xd8, 0x1e, 0xa0, 0x54, 0x96, 0x06, 0x7f,
	0xe3, 0x2b, 0x28, 0xc9, 0x60, 0xef, 0x48, 0xb0, 0x86, 0xc9, 0x3f, 0x9d, 0xe9, 0xd5, 0x1b, 0x4b,
	0xc3, 0xe4, 0xc4, 0x57, 0xc3, 0xe4, 0xaf, 0xce, 0xd4, 0x3e, 0x18, 0x80, 0x1a, 0xc7, 0xf4, 0x3a,
	0xf0, 0x2d, 0x54, 0x26, 0x45, 0xc1, 0x9a, 0x42, 0xfe, 0xef, 0xd6, 0xdd, 0xac, 0x7c, 0xaf, 0x3a,
	0x65, 0x49, 0xcf, 0xbb, 0xcd, 0x09, 0x0a, 0x65, 0xe9, 0xa3, 0x78, 0x09, 0x3f, 0x81, 0x0c, 0x52,
	0xf4, 0xd6, 0x3a, 0x01, 0xe7, 0xf0, 0x3d, 0x9a, 0x40, 0xa2, 0x88, 0x65, 0xcc, 0xad, 0x84, 0xc5,
	0x11, 0xd1, 0xe3, 0xd9, 0x85, 0x60, 0x7a, 0xc7, 0x05, 0x54, 0xd7, 0x14, 0xf3, 0x97, 0x33, 0x5e,
	0xca, 0x78, 0xfe, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0x01, 0xf2, 0xa9, 0x38, 0x0f, 0x01, 0x00,
	0x00,
}
