// Code generated by protoc-gen-go.
// source: service/service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service/service.proto

It has these top-level messages:
	Meta
	AllActions
	Targets
	SlotRange
	Slot
	Slots
	ErrorMessage
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meta struct {
	Version    uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Tag        string `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	CreateAt   uint32 `protobuf:"varint,3,opt,name=create_at,json=createAt" json:"create_at,omitempty"`
	Host       string `protobuf:"bytes,4,opt,name=host" json:"host,omitempty"`
	Username   string `protobuf:"bytes,5,opt,name=username" json:"username,omitempty"`
	Arch       string `protobuf:"bytes,6,opt,name=arch" json:"arch,omitempty"`
	Os         string `protobuf:"bytes,7,opt,name=os" json:"os,omitempty"`
	ZoneOffset int32  `protobuf:"varint,8,opt,name=zone_offset,json=zoneOffset" json:"zone_offset,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Meta) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Meta) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Meta) GetCreateAt() uint32 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *Meta) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Meta) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Meta) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Meta) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Meta) GetZoneOffset() int32 {
	if m != nil {
		return m.ZoneOffset
	}
	return 0
}

type AllActions struct {
	Actions []*AllActions_Act `protobuf:"bytes,1,rep,name=actions" json:"actions,omitempty"`
}

func (m *AllActions) Reset()                    { *m = AllActions{} }
func (m *AllActions) String() string            { return proto.CompactTextString(m) }
func (*AllActions) ProtoMessage()               {}
func (*AllActions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllActions) GetActions() []*AllActions_Act {
	if m != nil {
		return m.Actions
	}
	return nil
}

type AllActions_Act struct {
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Start  uint32 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	Last   uint32 `protobuf:"varint,3,opt,name=last" json:"last,omitempty"`
}

func (m *AllActions_Act) Reset()                    { *m = AllActions_Act{} }
func (m *AllActions_Act) String() string            { return proto.CompactTextString(m) }
func (*AllActions_Act) ProtoMessage()               {}
func (*AllActions_Act) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *AllActions_Act) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *AllActions_Act) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *AllActions_Act) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type Targets struct {
	Target []string `protobuf:"bytes,1,rep,name=target" json:"target,omitempty"`
}

func (m *Targets) Reset()                    { *m = Targets{} }
func (m *Targets) String() string            { return proto.CompactTextString(m) }
func (*Targets) ProtoMessage()               {}
func (*Targets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Targets) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

type SlotRange struct {
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Start  uint32 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End    uint32 `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
}

func (m *SlotRange) Reset()                    { *m = SlotRange{} }
func (m *SlotRange) String() string            { return proto.CompactTextString(m) }
func (*SlotRange) ProtoMessage()               {}
func (*SlotRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SlotRange) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *SlotRange) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *SlotRange) GetEnd() uint32 {
	if m != nil {
		return m.End
	}
	return 0
}

type Slot struct {
	Start uint32 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	Slot  uint32 `protobuf:"varint,2,opt,name=slot" json:"slot,omitempty"`
}

func (m *Slot) Reset()                    { *m = Slot{} }
func (m *Slot) String() string            { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()               {}
func (*Slot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Slot) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Slot) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

type Slots struct {
	Slots []*Slot `protobuf:"bytes,1,rep,name=slots" json:"slots,omitempty"`
}

func (m *Slots) Reset()                    { *m = Slots{} }
func (m *Slots) String() string            { return proto.CompactTextString(m) }
func (*Slots) ProtoMessage()               {}
func (*Slots) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Slots) GetSlots() []*Slot {
	if m != nil {
		return m.Slots
	}
	return nil
}

type ErrorMessage struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ErrorMessage) Reset()                    { *m = ErrorMessage{} }
func (m *ErrorMessage) String() string            { return proto.CompactTextString(m) }
func (*ErrorMessage) ProtoMessage()               {}
func (*ErrorMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ErrorMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Meta)(nil), "service.Meta")
	proto.RegisterType((*AllActions)(nil), "service.AllActions")
	proto.RegisterType((*AllActions_Act)(nil), "service.AllActions.Act")
	proto.RegisterType((*Targets)(nil), "service.Targets")
	proto.RegisterType((*SlotRange)(nil), "service.SlotRange")
	proto.RegisterType((*Slot)(nil), "service.Slot")
	proto.RegisterType((*Slots)(nil), "service.Slots")
	proto.RegisterType((*ErrorMessage)(nil), "service.ErrorMessage")
}

func init() { proto.RegisterFile("service/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcb, 0x6e, 0xdb, 0x30,
	0x10, 0x04, 0x2d, 0xc9, 0xb2, 0xd6, 0x75, 0x61, 0x10, 0x7d, 0x10, 0xee, 0xa1, 0xaa, 0x7a, 0xd1,
	0xa1, 0x70, 0xdb, 0xe4, 0x0b, 0x74, 0x08, 0x72, 0x08, 0x8c, 0x00, 0x4a, 0xee, 0x06, 0xa3, 0xac,
	0x65, 0x03, 0xb2, 0x18, 0x70, 0x37, 0x3e, 0xe4, 0x0b, 0xf2, 0x61, 0xf9, 0xb0, 0x80, 0x94, 0x64,
	0x23, 0xb9, 0xe5, 0xa4, 0x99, 0xd1, 0x70, 0x39, 0x1c, 0x2c, 0x7c, 0x25, 0xb4, 0x87, 0x5d, 0x85,
	0x7f, 0xfb, 0xef, 0xf2, 0xc1, 0x1a, 0x36, 0x32, 0xee, 0x69, 0xf6, 0x22, 0x20, 0x5c, 0x21, 0x6b,
	0xa9, 0x20, 0x3e, 0xa0, 0xa5, 0x9d, 0x69, 0x95, 0x48, 0x45, 0x3e, 0x2b, 0x07, 0x2a, 0xe7, 0x10,
	0xb0, 0xae, 0xd5, 0x28, 0x15, 0x79, 0x52, 0x3a, 0x28, 0x7f, 0x40, 0x52, 0x59, 0xd4, 0x8c, 0x6b,
	0xcd, 0x2a, 0xf0, 0xee, 0x49, 0x27, 0x14, 0x2c, 0x25, 0x84, 0x5b, 0x43, 0xac, 0x42, 0xef, 0xf7,
	0x58, 0x2e, 0x60, 0xf2, 0x48, 0x68, 0x5b, 0xbd, 0x47, 0x15, 0x79, 0xfd, 0xc8, 0x9d, 0x5f, 0xdb,
	0x6a, 0xab, 0xc6, 0x9d, 0xdf, 0x61, 0xf9, 0x19, 0x46, 0x86, 0x54, 0xec, 0x95, 0x91, 0x21, 0xf9,
	0x13, 0xa6, 0x4f, 0xa6, 0xc5, 0xb5, 0xd9, 0x6c, 0x08, 0x59, 0x4d, 0x52, 0x91, 0x47, 0x25, 0x38,
	0xe9, 0xda, 0x2b, 0xd9, 0xb3, 0x00, 0x28, 0x9a, 0xa6, 0xa8, 0x78, 0x67, 0x5a, 0x92, 0xff, 0x21,
	0xd6, 0x1d, 0x54, 0x22, 0x0d, 0xf2, 0xe9, 0xd9, 0xf7, 0xe5, 0xf0, 0xfe, 0x93, 0x6b, 0x59, 0x54,
	0x5c, 0x0e, 0xbe, 0xc5, 0x25, 0x04, 0x45, 0xc5, 0xf2, 0x1b, 0x8c, 0x59, 0xdb, 0x1a, 0xd9, 0xb7,
	0x90, 0x94, 0x3d, 0x93, 0x5f, 0x20, 0x22, 0xd6, 0x96, 0x7d, 0x0d, 0xb3, 0xb2, 0x23, 0x2e, 0x7b,
	0xa3, 0x69, 0xe8, 0xc0, 0xe3, 0xec, 0x17, 0xc4, 0xb7, 0xfe, 0x0c, 0xbd, 0x19, 0x16, 0x9c, 0x86,
	0x65, 0x57, 0x90, 0xdc, 0x34, 0x86, 0x4b, 0xdd, 0xd6, 0xf8, 0xc1, 0x1b, 0xe7, 0x10, 0x60, 0x7b,
	0xdf, 0x5f, 0xe8, 0x60, 0xf6, 0x0f, 0x42, 0x37, 0xec, 0xe4, 0x17, 0xef, 0x12, 0x52, 0x63, 0x86,
	0x21, 0x1e, 0x67, 0x7f, 0x20, 0x72, 0x27, 0x48, 0xfe, 0x86, 0xc8, 0x09, 0x43, 0x49, 0xb3, 0x63,
	0x49, 0x3e, 0x5d, 0xf7, 0x2f, 0xcb, 0xe1, 0xd3, 0x85, 0xb5, 0xc6, 0xae, 0x90, 0x48, 0xd7, 0xe8,
	0x16, 0x65, 0xdf, 0xc1, 0x3e, 0xf0, 0x40, 0xef, 0xc6, 0x7e, 0xb7, 0xce, 0x5f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xf8, 0x06, 0xa0, 0xe2, 0x74, 0x02, 0x00, 0x00,
}
