// Code generated by protoc-gen-go.
// source: db.proto
// DO NOT EDIT!

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	Meta
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meta struct {
	Version  int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Arch     string `protobuf:"bytes,3,opt,name=arch" json:"arch,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	Os       string `protobuf:"bytes,5,opt,name=os" json:"os,omitempty"`
	CreateAt int64  `protobuf:"varint,6,opt,name=create_at,json=createAt" json:"create_at,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Meta) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Meta) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Meta) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Meta) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Meta) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Meta) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Meta)(nil), "Meta")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x49, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0x9a, 0xc8, 0xc8, 0xc5, 0xe2, 0x9b, 0x5a, 0x92, 0x28, 0x24, 0xc1,
	0xc5, 0x5e, 0x96, 0x5a, 0x54, 0x9c, 0x99, 0x9f, 0x27, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0x04,
	0xe3, 0x0a, 0x09, 0x71, 0xb1, 0x64, 0xe4, 0x17, 0x97, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06,
	0x81, 0xd9, 0x20, 0xb1, 0xc4, 0xa2, 0xe4, 0x0c, 0x09, 0x66, 0x88, 0x18, 0x88, 0x2d, 0x24, 0xc5,
	0xc5, 0x51, 0x5a, 0x9c, 0x5a, 0x94, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x02, 0x16, 0x87, 0xf3, 0x85,
	0xf8, 0xb8, 0x98, 0xf2, 0x8b, 0x25, 0x58, 0xc1, 0xa2, 0x4c, 0xf9, 0xc5, 0x42, 0xd2, 0x5c, 0x9c,
	0xc9, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0xf1, 0x89, 0x25, 0x12, 0x6c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41,
	0x1c, 0x10, 0x01, 0xc7, 0x92, 0x24, 0x36, 0xb0, 0xd3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x19, 0x54, 0x0e, 0x21, 0xa6, 0x00, 0x00, 0x00,
}
